from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field


class FunctionCall(BaseModel):
    name: str
    arguments: str


class ChatCompletionToolCall(BaseModel):
    id: str
    type: str = "function"
    function: FunctionCall


class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message author (e.g., system, user, assistant, tool)")
    content: Optional[Union[str, List[Any]]] = Field(None, description="The contents of the message")
    name: Optional[str] = Field(None, description="An optional name for the participant")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Tool calls generated by the assistant")
    tool_call_id: Optional[str] = Field(None, description="Tool call that this message is responding to")
    reasoning_content: Optional[str] = Field(None, description="Reasoning or thinking content generated by reasoning models")
    refusal: Optional[str] = Field(None, description="Refusal message if response was refused")

    model_config = {
        "extra": "allow"
    }


class ChatCompletionRequest(BaseModel):
    messages: List[ChatMessage]
    model: Optional[str] = None
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    max_tokens: Optional[int] = None
    stream: Optional[bool] = False
    stop: Optional[Union[str, List[str]]] = None
    tools: Optional[List[Dict[str, Any]]] = None
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None
    response_format: Optional[Dict[str, Any]] = None
    stream_options: Optional[Dict[str, Any]] = None
    user: Optional[str] = None
    presence_penalty: Optional[float] = None
    frequency_penalty: Optional[float] = None
    n: Optional[int] = 1

    model_config = {
        "extra": "allow"
    }


class ChatCompletionChoiceMessage(BaseModel):
    role: str = "assistant"
    content: Optional[str] = None
    reasoning_content: Optional[str] = None
    tool_calls: Optional[List[ChatCompletionToolCall]] = None
    refusal: Optional[str] = None


class ChatCompletionChoice(BaseModel):
    index: int = 0
    message: ChatCompletionChoiceMessage
    finish_reason: Optional[str] = "stop"


class ChatCompletionUsage(BaseModel):
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class ChatCompletionResponse(BaseModel):
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: List[ChatCompletionChoice]
    usage: ChatCompletionUsage


class ChoiceDeltaFunctionCall(BaseModel):
    name: Optional[str] = None
    arguments: Optional[str] = None


class ChoiceDeltaToolCall(BaseModel):
    index: int = 0
    id: Optional[str] = None
    type: Optional[str] = "function"
    function: Optional[ChoiceDeltaFunctionCall] = None


class ChatCompletionChunkDelta(BaseModel):
    role: Optional[str] = None
    content: Optional[str] = None
    reasoning_content: Optional[str] = None
    tool_calls: Optional[List[ChoiceDeltaToolCall]] = None
    refusal: Optional[str] = None


class ChatCompletionChunkChoice(BaseModel):
    index: int = 0
    delta: ChatCompletionChunkDelta
    finish_reason: Optional[str] = None


class ChatCompletionChunk(BaseModel):
    id: str
    object: str = "chat.completion.chunk"
    created: int
    model: str
    choices: List[ChatCompletionChunkChoice]


class CompletionRequest(BaseModel):
    prompt: Union[str, List[str], List[int], List[List[int]]]
    model: Optional[str] = None
    suffix: Optional[str] = None
    max_tokens: Optional[int] = None
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    n: Optional[int] = 1
    stream: Optional[bool] = False
    logprobs: Optional[int] = None
    echo: Optional[bool] = False
    stop: Optional[Union[str, List[str]]] = None
    presence_penalty: Optional[float] = None
    frequency_penalty: Optional[float] = None
    user: Optional[str] = None

    model_config = {
        "extra": "allow"
    }


class CompletionChoice(BaseModel):
    index: int = 0
    text: str
    logprobs: Optional[Any] = None
    finish_reason: Optional[str] = "stop"


class CompletionUsage(BaseModel):
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class CompletionResponse(BaseModel):
    id: str
    object: str = "text_completion"
    created: int
    model: str
    choices: List[CompletionChoice]
    usage: CompletionUsage


class CompletionChunkChoice(BaseModel):
    index: int = 0
    text: str
    logprobs: Optional[Any] = None
    finish_reason: Optional[str] = None


class CompletionChunk(BaseModel):
    id: str
    object: str = "text_completion"
    created: int
    model: str
    choices: List[CompletionChunkChoice]


import time


class ModelInfo(BaseModel):
    id: str
    object: str = "model"
    created: int = Field(default_factory=lambda: int(time.time()))
    owned_by: str = "iris-engine"


class ModelList(BaseModel):
    object: str = "list"
    data: List[ModelInfo]


