from prometheus_client import Counter, Gauge, Histogram

# Total request counters
REQUESTS_TOTAL = Counter(
    "mlx_server_requests_total",
    "Total number of requests processed by the server",
    ["status"]  # status="success" | "error"
)

# Active state gauges
QUEUE_LENGTH = Gauge(
    "mlx_server_queue_length",
    "Current number of requests waiting in the batching scheduler queue"
)

ACTIVE_GENERATIONS = Gauge(
    "mlx_server_active_generations",
    "Current number of sequences actively generating in the inference worker"
)

BATCH_SIZE = Histogram(
    "mlx_server_batch_size",
    "Distribution of batch sizes processed by the inference worker",
    buckets=[1, 2, 4, 8, 12, 16, 24, 32]
)

# Latency histograms
REQUEST_LATENCY_SECONDS = Histogram(
    "mlx_server_request_latency_seconds",
    "End-to-end request latency in seconds",
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0]
)

TIME_TO_FIRST_TOKEN_SECONDS = Histogram(
    "mlx_server_time_to_first_token_seconds",
    "Time from request queueing to first generated token",
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0]
)

# Token stats
PROMPT_TOKENS_TOTAL = Counter(
    "mlx_server_prompt_tokens_total",
    "Total number of prompt tokens processed"
)

GENERATED_TOKENS_TOTAL = Counter(
    "mlx_server_generated_tokens_total",
    "Total number of tokens generated by the model"
)

TOKENS_GENERATED_SPEED = Histogram(
    "mlx_server_tokens_generated_speed_tps",
    "Tokens per second generated during generation phase",
    buckets=[5, 10, 15, 20, 25, 30, 40, 50, 75, 100]
)

# Cache stats
CACHE_HITS_TOTAL = Counter(
    "mlx_server_cache_hits_total",
    "Total number of prompt cache hits (reused KV tokens)"
)

CACHE_MISSES_TOTAL = Counter(
    "mlx_server_cache_misses_total",
    "Total number of prompt cache misses"
)
